### PR TITLE
First pull request - Submitting "Hello Microverse" Project for code review

### PR DESCRIPTION
**Pull request by barath-7**
This is the first Microverse project I created.

### CODE REVIEW

**Review by AshakaE — CHANGES_REQUESTED** [review]
## Hi @barath-7 , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Please fix the linter error
- [x] Please make your pull requests more descriptive.
- [ ] Please try to make your readme file more robust, you can make use of the Microverse readme template and edit the necessary fields.
- [ ] when making your next commit, I suggest you use present tense, _example_ instead of `added HTML file` rather `Add HTML file` 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by barath-7** [comment]
Hi AshakaE,
Thanks for the comments. 
I have two queries,
1. Even after following the steps mentioned in the below URL, I can't seem to rectify the linter error. Can you please give me some suggestions on that.
https://github.com/microverseinc/linters-config/tree/master/html-css#troubleshooting

2.And also any suggestion on how to make pull request more descriptive

**Comment by barath-7** [comment]
> ## Hi @barath-7 ,
> Good job so far! 👏
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * [ ]  Please fix the linter error
> * [ ]  Please make your pull requests more descriptive.
> * [ ]  Please try to make your readme file more robust, you can make use of the Microverse readme template and edit the necessary fields.
> * [ ]  when making your next commit, I suggest you use present tense, _example_ instead of `added HTML file` rather `Add HTML file`
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

Hi AshakaE,
Thanks for the comments.
I have two queries,

Even after following the steps mentioned in the below URL, I can't seem to rectify the linter error. Can you please give me some suggestions on that.
https://github.com/microverseinc/linters-config/tree/master/html-css#troubleshooting
2.And also any suggestion on how to make pull request more descriptive

**Comment by barath-7** [comment]
linter error is fixed now and changes made to readme file as suggested

**Review by Shaher-11 — APPROVED** [review]
#### Hello @barath-7,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Pull request merged**
